[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink=lib/chainlink/contracts",
    "@openzeppelin=lib/openzeppelin-contracts",
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
optimizer = true
optimizer_runs = 200 # You can adjust this number
via_ir = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
